In [1]:
import sklearn

In [2]:
sklearn.__version__

'0.24.2'

In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

In [5]:
iris = load_iris()

In [7]:
type(iris)

sklearn.utils.Bunch

In [9]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [10]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [14]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [15]:
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)
iris_df.head(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2

In [16]:
iris_df['label']=iris.target

In [17]:
iris_df.sample(2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
95                5.7               3.0                4.2               1.2   
9                 4.9               3.1                1.5               0.1   

    label  
95      1  
9       0

In [19]:
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                                                iris.target,
                                                test_size=0.2,
                                                random_state=11)

In [20]:
X_train.shape,X_test.shape

((120, 4), (30, 4))

In [22]:
X_test,y_test

(array([[6.8, 3. , 5.5, 2.1],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.8, 5.1, 1.5],
        [6.3, 3.3, 4.7, 1.6],
        [6.4, 2.7, 5.3, 1.9],
        [4.9, 3.1, 1.5, 0.1],
        [6.7, 3.1, 4.4, 1.4],
        [5.7, 4.4, 1.5, 0.4],
        [4.8, 3.1, 1.6, 0.2],
        [6.1, 2.9, 4.7, 1.4],
        [6. , 2.2, 5. , 1.5],
        [6. , 2.2, 4. , 1. ],
        [5.4, 3. , 4.5, 1.5],
        [5.7, 2.5, 5. , 2. ],
        [6.9, 3.1, 5.4, 2.1],
        [4.5, 2.3, 1.3, 0.3],
        [6.3, 2.9, 5.6, 1.8],
        [5.6, 3. , 4.5, 1.5],
        [6.5, 3.2, 5.1, 2. ],
        [5.8, 2.7, 5.1, 1.9],
        [5.6, 2.5, 3.9, 1.1],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.6, 1. , 0.2],
        [6.4, 3.2, 4.5, 1.5],
        [4.8, 3. , 1.4, 0.1],
        [4.8, 3.4, 1.6, 0.2],
        [5.9, 3. , 5.1, 1.8],
        [6.6, 3. , 4.4, 1.4],
        [5.4, 3.9, 1.3, 0.4],
        [6. , 3.4, 4.5, 1.6]]),
 array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
        0, 1, 0, 0, 2, 1

In [23]:
dt_clf = DecisionTreeClassifier(random_state=11)

In [24]:
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [25]:
pred = dt_clf.predict(X_test)

In [26]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [27]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
accuracy_score(y_test,pred)

0.9333333333333333

In [30]:
# 데이터 분리없이

In [31]:
iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data,train_label)

DecisionTreeClassifier()

In [32]:
pred = dt_clf.predict(train_data)

In [33]:
accuracy_score(train_label,pred)

1.0

# K폴드

![](/img/ww.png)

In [34]:
from sklearn.model_selection import KFold
import numpy as np

In [35]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [43]:
kfold = KFold(n_splits=5)
cv_accuracy = []

In [49]:
n_iter = 0
for train_index, test_index in kfold.split(iris.data):
    # print(train_index, test_index)
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'\n{n_iter} 교차검증 정확도 : {accuracy},학습데이터 크기 : {train_size},검증 데이터 크기 : {test_size}')
    print(f'{n_iter} 검증데이터 인덱스 : {test_index}')
    cv_accuracy.append(accuracy)


1 교차검증 정확도 : 1.0,학습데이터 크기 : 120,검증 데이터 크기 : 30
1 검증데이터 인덱스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

2 교차검증 정확도 : 0.9667,학습데이터 크기 : 120,검증 데이터 크기 : 30
2 검증데이터 인덱스 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

3 교차검증 정확도 : 0.8667,학습데이터 크기 : 120,검증 데이터 크기 : 30
3 검증데이터 인덱스 : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

4 교차검증 정확도 : 0.9333,학습데이터 크기 : 120,검증 데이터 크기 : 30
4 검증데이터 인덱스 : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

5 교차검증 정확도 : 0.7333,학습데이터 크기 : 120,검증 데이터 크기 : 30
5 검증데이터 인덱스 : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]


In [52]:
np.mean(cv_accuracy)

0.9

In [53]:
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [54]:
from sklearn.model_selection import StratifiedKFold


In [57]:
skf = StratifiedKFold(n_splits=3)
n_iter = 0
for train_index, test_index in skf.split(iris_df,iris_df['label']):
    X_train,X_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print(f'\n{n_iter} 교차검증 정확도 : {accuracy},학습데이터 크기 : {train_size},검증 데이터 크기 : {test_size}')
    print(f'{n_iter} 검증데이터 인덱스 : {test_index}')
    cv_accuracy.append(accuracy)


1 교차검증 정확도 : 0.98,학습데이터 크기 : 100,검증 데이터 크기 : 50
1 검증데이터 인덱스 : [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

2 교차검증 정확도 : 0.94,학습데이터 크기 : 100,검증 데이터 크기 : 50
2 검증데이터 인덱스 : [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

3 교차검증 정확도 : 0.98,학습데이터 크기 : 100,검증 데이터 크기 : 50
3 검증데이터 인덱스 : [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]


In [58]:
from sklearn.model_selection import cross_val_score

In [59]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [60]:
cross_val_score(dt_clf,iris.data,iris.target,scoring='accuracy',cv=3)

array([0.98, 0.94, 0.98])

In [62]:
grid_parameters = {'max_depth':[1,2,3],
                  'min_samples_split':[2,3]}

In [ ]:
from sklearn.model_selection import GridSearchCV

In [64]:
iris = load_iris()
X_train,X_test,y_train,y_test = train_test_split(iris.data,
                                                iris.target,
                                                test_size=0.2,
                                                random_state=121)

dt_clf=DecisionTreeClassifier()

In [69]:
grid_dtree = GridSearchCV(dt_clf,param_grid=grid_parameters,cv=3,refit=True)
grid_dtree.fit(X_train,y_train)
scoreds_df = pd.DataFrame(grid_dtree.cv_results_)

In [70]:
scoreds_df[['params','mean_test_score','rank_test_score','split0_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  
0              0.700  
1              0.700  
2              0.925  
3              0.925  
4              0.975  
5              0.975

In [71]:
from sklearn.preprocessing import LabelEncoder

In [72]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

In [73]:
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [74]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [76]:
encoder.inverse_transform([4,5,2,0,1,1,3,3])

array(['전자레인지', '컴퓨터', '믹서', 'TV', '냉장고', '냉장고', '선풍기', '선풍기'],
      dtype='<U5')

In [77]:
from sklearn.preprocessing import OneHotEncoder

In [78]:
labels = labels.reshape(-1,1)

In [79]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

In [80]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [81]:
oh_labels.shape

(8, 6)

In [82]:
df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})

In [83]:
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [84]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

In [85]:
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data,columns=iris.feature_names)

In [86]:
iris_df.mean()

sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

In [87]:
iris_df.var()

sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [88]:
from sklearn.preprocessing import MinMaxScaler

In [89]:
scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
iris_df_scaled = pd.DataFrame(data=iris_scaled,columns = iris.feature_names)

In [93]:
iris_df.min(),iris_df.max()

(sepal length (cm)    4.3
 sepal width (cm)     2.0
 petal length (cm)    1.0
 petal width (cm)     0.1
 dtype: float64,
 sepal length (cm)    7.9
 sepal width (cm)     4.4
 petal length (cm)    6.9
 petal width (cm)     2.5
 dtype: float64)

In [94]:
iris_df_scaled.min(),iris_df_scaled.max()

(sepal length (cm)    0.0
 sepal width (cm)     0.0
 petal length (cm)    0.0
 petal width (cm)     0.0
 dtype: float64,
 sepal length (cm)    1.0
 sepal width (cm)     1.0
 petal length (cm)    1.0
 petal width (cm)     1.0
 dtype: float64)

In [95]:
train_array = np.arange(11).reshape(-1,1)
test_array = np.arange(6).reshape(-1,1)

In [96]:
train_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [97]:
test_array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [98]:
scaler = MinMaxScaler()

In [99]:
scaler.fit(train_array)

MinMaxScaler()

In [100]:
scaler.transform(train_array)

array([[0. ],
       [0.1],
       [0.2],
       [0.3],
       [0.4],
       [0.5],
       [0.6],
       [0.7],
       [0.8],
       [0.9],
       [1. ]])